from pydantic import BaseModel, Field

class LLMTestRequest(BaseModel):
    message: str = Field(..., description="The prompt/message to send to the Gemini model.")

class LLMTestResponse(BaseModel):
    response: str = Field(..., description="The response generated by the Gemini model.")
